Ensure localdisk storage returns a path
Without this, the URL field is a TextIOWrapper. Therefore, the moment
we try to upload anything, it fails - json.dumps in 'def produce' can't
turn that kind of object into a JSON.

Here's how the hash looks like:

upload-service_1  | ERROR:tornado.application:{'principal':
  'default_principal', 'rh_account': '000001', 'hash':
    '74d74f211ab04e8db62180ee866632d5', 'url': <_io.TextIOWrapper
    name='/tmp/uploads/insights-upload-quarantine/74d74f211ab04e8'
    mode='w' enco    ding='UTF-8'>, 'validation': 1, 'size': 3882,
    'service': 'testareno'}

TypeError: Object of type 'TextIOWrapper' is not JSON serializable